const API="/api",form=document.getElementById("form"),msg=document.getElementById("msg"),leaderboardBtn=document.getElementById("leaderboardBtn"),leaderboardCard=document.getElementById("leaderboardCard"),premiumRow=document.getElementById("premiumRow"),premiumRequired=document.getElementById("premiumRequired"),authScreen=document.getElementById("authScreen"),trackerApp=document.getElementById("trackerApp"),authForm=document.getElementById("authForm"),authEmail=document.getElementById("authEmail"),authPassword=document.getElementById("authPassword"),authMsg=document.getElementById("authMsg"),authSubmit=document.getElementById("authSubmit"),registerBtn=document.getElementById("registerBtn"),logoutBtn=document.getElementById("logoutBtn"),authTitle=document.getElementById("authTitle"),authSubtitle=document.getElementById("authSubtitle");
const esc=x=>{const d=document.createElement("div");d.textContent=x;return d.innerHTML};
let authToken=localStorage.getItem("expenseTrackerToken");
let currentUser=JSON.parse(localStorage.getItem("expenseTrackerUser")||"null");
function authHeaders(){return authToken?{Authorization:`Bearer ${authToken}`}:{}}
function setAuth(data){authToken=data.token;currentUser=data.user;localStorage.setItem("expenseTrackerToken",authToken);localStorage.setItem("expenseTrackerUser",JSON.stringify(currentUser));updatePremiumState()}
function updatePremiumState(){const premium=Boolean(currentUser?.isPremium);authScreen.hidden=Boolean(currentUser);trackerApp.hidden=!currentUser;premiumRow.hidden=!premium;premiumRequired.hidden=premium;if(!premium){leaderboardCard.hidden=true;leaderboardBtn.textContent="Show Leaderboard"}}
logoutBtn.addEventListener("click",()=>{authToken=null;currentUser=null;localStorage.removeItem("expenseTrackerToken");localStorage.removeItem("expenseTrackerUser");updatePremiumState();authMsg.textContent="You have been logged out."});
leaderboardBtn.addEventListener("click",async()=>{const isHidden=leaderboardCard.hidden;if(isHidden){leaderboardBtn.disabled=true;leaderboardBtn.textContent="Loading...";await loadLeaderboard();leaderboardBtn.disabled=false;leaderboardCard.hidden=false;leaderboardBtn.textContent="Hide Leaderboard";leaderboardCard.scrollIntoView({behavior:"smooth",block:"start"})}else{leaderboardCard.hidden=true;leaderboardBtn.textContent="Show Leaderboard"}});
async function load(){const r=await fetch(API+"/expenses"),xs=await r.json();let t=0;list.innerHTML="";xs.forEach(x=>{t+=+x.amount;const d=document.createElement("div");d.className="expense";d.innerHTML=`<div><b>${esc(x.description)}</b><div class="meta"><span class="cat">${esc(x.category)}</span>${x.aiSuggested?'<span class="ai"> • AI suggested</span>':""} • ${new Date(x.createdAt).toLocaleDateString()}</div></div><div><b>₹${(+x.amount).toFixed(2)}</b> <button class="del" onclick="del(${x.id})">Delete</button></div>`;list.appendChild(d)});total.textContent=`Total: ₹${t.toFixed(2)}`}
async function loadLeaderboard(){try{const r=await fetch(API+"/expenses/leaderboard",{headers:authHeaders()});const data=await r.json();if(!r.ok)throw new Error(data.message||"Unable to load leaderboard");leaderboardTotal.textContent=`${data.leaderboard.length} users`;if(!data.leaderboard.length){leaderboard.innerHTML='<div class="empty-state">No user expenses yet.</div>';return}const max=data.leaderboard[0].totalExpense;leaderboard.innerHTML=`<div class="rank-list">${data.leaderboard.map(row=>`<div class="rank-row"><span class="rank-number">#${row.rank}</span><span class="rank-category">${esc(row.email)}</span><span class="rank-track"><i style="width:${Math.max(8,row.totalExpense/max*100)}%"></i></span><b>₹${row.totalExpense.toFixed(2)}</b></div>`).join("")}</div>`}catch(e){leaderboard.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`}}
authForm.onsubmit=async e=>{e.preventDefault();authMsg.textContent="Logging in...";try{const r=await fetch(API+"/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:authEmail.value,password:authPassword.value})});const data=await r.json();if(!r.ok){authMsg.textContent=data.message||"Login failed";return}setAuth(data);authMsg.textContent="Login successful";authForm.reset()}catch(error){authMsg.textContent="Server is not available. Start the backend and try again."}};
registerBtn.onclick=async()=>{const email=authEmail.value.trim(),password=authPassword.value;if(!email){authMsg.textContent="Please enter your email address.";authEmail.focus();return}if(password.length<6){authMsg.textContent="Password must be at least 6 characters.";authPassword.focus();return}authMsg.textContent="Creating your account...";try{const r=await fetch(API+"/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok){authMsg.textContent=data.message||"Registration failed";return}setAuth(data);authMsg.textContent="Account created";authForm.reset()}catch(error){authMsg.textContent="Server is not available. Start the backend and try again."}};
form.onsubmit=async e=>{e.preventDefault();msg.textContent="AI is categorizing...";const body={amount:+amount.value,description:description.value.trim()};if(category.value)body.category=category.value;const r=await fetch(API+"/expenses",{method:"POST",headers:{"Content-Type":"application/json",...authHeaders()},body:JSON.stringify(body)}),x=await r.json();msg.textContent=r.ok?(x.aiSuggested?`AI category: ${x.category}`:"Expense added."):(x.message||"Error");if(r.ok){form.reset();load()}};
async function del(id){if(confirm("Delete this expense?")){await fetch(API+"/expenses/"+id,{method:"DELETE"});load()}}
insightBtn.onclick=async()=>{insight.innerHTML='<div class="insight">AI is analyzing...</div>';const r=await fetch(API+"/ai/insight"),x=await r.json();insight.innerHTML=`<div class="insight">✨ ${esc(x.insight||x.message)}</div>`};
updatePremiumState();
load();
