const API=(import.meta.env.VITE_API_URL||"/api").replace(/\/+$/,""),form=document.getElementById("form"),msg=document.getElementById("msg"),leaderboardBtn=document.getElementById("leaderboardBtn"),leaderboardCard=document.getElementById("leaderboardCard"),premiumRow=document.getElementById("premiumRow"),premiumRequired=document.getElementById("premiumRequired"),authScreen=document.getElementById("authScreen"),trackerApp=document.getElementById("trackerApp"),authForm=document.getElementById("authForm"),authEmail=document.getElementById("authEmail"),authPassword=document.getElementById("authPassword"),authMsg=document.getElementById("authMsg"),authSubmit=document.getElementById("authSubmit"),registerBtn=document.getElementById("registerBtn"),logoutBtn=document.getElementById("logoutBtn"),authTitle=document.getElementById("authTitle"),authSubtitle=document.getElementById("authSubtitle");
const esc=x=>{const d=document.createElement("div");d.textContent=x;return d.innerHTML};
async function request(path,options={}){const url=API+(path.startsWith("/api/")?path.slice(4):path);let response;try{response=await fetch(url,options)}catch(error){throw new Error("Unable to reach the backend. Check the deployed API URL and CORS settings.")}let data;try{data=await response.json()}catch(error){throw new Error(`Backend returned an invalid response (${response.status}).`)}if(!response.ok)throw new Error(data.message||`Request failed (${response.status}).`);return data}
let authToken=localStorage.getItem("expenseTrackerToken");
let currentUser=JSON.parse(localStorage.getItem("expenseTrackerUser")||"null");
let authMode="login";
function authHeaders(){return authToken?{Authorization:`Bearer ${authToken}`}:{}}
function setAuth(data){authToken=data.token;currentUser=data.user;localStorage.setItem("expenseTrackerToken",authToken);localStorage.setItem("expenseTrackerUser",JSON.stringify(currentUser));updatePremiumState()}
function clearAuth(){authToken=null;currentUser=null;localStorage.removeItem("expenseTrackerToken");localStorage.removeItem("expenseTrackerUser");updatePremiumState()}
function updatePremiumState(){const premium=Boolean(currentUser?.isPremium);authScreen.hidden=Boolean(currentUser);trackerApp.hidden=!currentUser;premiumRow.hidden=!premium;premiumRequired.hidden=premium;if(!premium){leaderboardCard.hidden=true;leaderboardBtn.textContent="Show Leaderboard"}}
function setAuthMode(mode){authMode=mode;const signup=mode==="register";authTitle.textContent=signup?"Create your account":"Welcome back";authSubtitle.textContent=signup?"Start tracking your expenses":"Sign in to continue to your expenses";authSubmit.textContent=signup?"Create account":"Login";registerBtn.textContent=signup?"Back to login":"Create a new account";authMsg.textContent=""}
logoutBtn.addEventListener("click",()=>{authToken=null;currentUser=null;localStorage.removeItem("expenseTrackerToken");localStorage.removeItem("expenseTrackerUser");updatePremiumState();authMsg.textContent="You have been logged out."});
leaderboardBtn.addEventListener("click",async()=>{const isHidden=leaderboardCard.hidden;if(isHidden){leaderboardBtn.disabled=true;leaderboardBtn.textContent="Loading...";await loadLeaderboard();leaderboardBtn.disabled=false;leaderboardCard.hidden=false;leaderboardBtn.textContent="Hide Leaderboard";leaderboardCard.scrollIntoView({behavior:"smooth",block:"start"})}else{leaderboardCard.hidden=true;leaderboardBtn.textContent="Show Leaderboard"}});
async function load(){try{const xs=await request("/api/expenses");let t=0;list.innerHTML="";xs.forEach(x=>{t+=+x.amount;const d=document.createElement("div");d.className="expense";d.innerHTML=`<div><b>${esc(x.description)}</b><div class="meta"><span class="cat">${esc(x.category)}</span>${x.aiSuggested?'<span class="ai"> • AI suggested</span>':""} • ${new Date(x.createdAt).toLocaleDateString()}</div></div><div><b>₹${(+x.amount).toFixed(2)}</b> <button class="del" onclick="del(${x.id})">Delete</button></div>`;list.appendChild(d)});total.textContent=`Total: ₹${t.toFixed(2)}`}catch(error){list.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`}}
async function loadLeaderboard(){try{const data=await request("/api/expenses/leaderboard",{headers:authHeaders()});leaderboardTotal.textContent=`${data.leaderboard.length} users`;if(!data.leaderboard.length){leaderboard.innerHTML='<div class="empty-state">No user expenses yet.</div>';return}const max=data.leaderboard[0].totalExpense;leaderboard.innerHTML=`<div class="rank-list">${data.leaderboard.map(row=>`<div class="rank-row"><span class="rank-number">#${row.rank}</span><span class="rank-category">${esc(row.email)}</span><span class="rank-track"><i style="width:${Math.max(8,row.totalExpense/max*100)}%"></i></span><b>₹${row.totalExpense.toFixed(2)}</b></div>`).join("")}</div>`}catch(e){leaderboard.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`}}
authForm.onsubmit=async e=>{e.preventDefault();const email=authEmail.value.trim().toLowerCase(),password=authPassword.value;if(!email){authMsg.textContent="Please enter your email address.";authEmail.focus();return}if(password.length<6){authMsg.textContent="Password must be at least 6 characters.";authPassword.focus();return}authSubmit.disabled=true;registerBtn.disabled=true;authMsg.textContent=authMode==="register"?"Creating your account...":"Logging in...";try{const path=authMode==="register"?"/api/auth/register":"/api/auth/login";const data=await request(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});if(authMode==="register"){clearAuth();authForm.reset();setAuthMode("login");authEmail.value=email;authMsg.textContent="Account created. Please login to continue."}else{setAuth(data);authMsg.textContent="Login successful";authForm.reset()}}catch(error){authMsg.textContent=error.message}finally{authSubmit.disabled=false;registerBtn.disabled=false}};
registerBtn.onclick=()=>{setAuthMode(authMode==="register"?"login":"register");if(authMode==="register")authEmail.focus()};
form.onsubmit=async e=>{e.preventDefault();msg.textContent="AI is categorizing...";const body={amount:+amount.value,description:description.value.trim()};if(category.value)body.category=category.value;try{const x=await request("/api/expenses",{method:"POST",headers:{"Content-Type":"application/json",...authHeaders()},body:JSON.stringify(body)});msg.textContent=x.aiSuggested?`AI category: ${x.category}`:"Expense added.";form.reset();load()}catch(error){msg.textContent=error.message}};
async function del(id){if(confirm("Delete this expense?")){try{await request("/api/expenses/"+id,{method:"DELETE"});load()}catch(error){msg.textContent=error.message}}}
window.del=del;
insightBtn.onclick=async()=>{insight.innerHTML='<div class="insight">AI is analyzing...</div>';try{const x=await request("/api/ai/insight");insight.innerHTML=`<div class="insight">✨ ${esc(x.insight||x.message)}</div>`}catch(error){insight.innerHTML=`<div class="empty-state">${esc(error.message)}</div>`}};
updatePremiumState();
load();
